Repository leoAshu/crypter, pull requests merged in 2025-07, with the labels that each got.

#5 Setup Issue and PR Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#4 Refactor Icon Button Styling Logic
  frontend/app/(auth)/index.tsx
  frontend/app/(auth)/signup.tsx
  frontend/components/IconButton.tsx
Labels: bug, enhancement

#7 Adds Light theme styling to RoundIconButton
  frontend/components/RoundIconButton.tsx
Labels: bug

#9 Simplifies Tailwind Color Naming and Theme Handling
  frontend/.prettierrc
  frontend/app/(auth)/index.tsx
  frontend/app/(auth)/signup.tsx
  frontend/app/globals.css
  frontend/app/index.tsx
  frontend/components/IconButton.tsx
  frontend/components/InputField.tsx
  frontend/components/PrimaryButton.tsx
  frontend/components/RoundIconButton.tsx
  frontend/tailwind.config.js
Labels: enhancement

#19 Enforce Prettier Format Check on PRs
  .github/workflows/prettier.yml
  package-lock.json
  package.json
Labels: feature

#34 Design Account Tab & Profile Routes
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(auth)/signup.tsx
  apps/frontend/app/(auth)/signupInfo.tsx
  apps/frontend/app/(auth)/welcome.tsx
  apps/frontend/app/(profile)/_layout.tsx
  apps/frontend/app/(profile)/index.tsx
  apps/frontend/app/(profile)/updateProfile.tsx
  apps/frontend/app/(tabs)/account.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/app/globals.css
  apps/frontend/assets/images/arrow-left.png
  apps/frontend/assets/images/edit.png
  apps/frontend/assets/images/next.png
  apps/frontend/assets/index.ts
  apps/frontend/components/TabScreenWrapper.tsx
  apps/frontend/components/account/AccountInfo.tsx
  apps/frontend/components/account/index.ts
  apps/frontend/components/avatars/InitialsAvatar.tsx
  apps/frontend/components/avatars/index.ts
  apps/frontend/components/buttons/IconButton.tsx
  apps/frontend/components/buttons/PrimaryButton.tsx
  apps/frontend/components/buttons/RoundIconButton.tsx
  apps/frontend/components/buttons/SecondaryButton.tsx
  apps/frontend/components/buttons/index.ts
  apps/frontend/components/form/InputField.tsx
  apps/frontend/components/form/index.ts
  apps/frontend/components/index.ts
  apps/frontend/components/menu/MenuOption.tsx
  apps/frontend/components/menu/index.ts
  apps/frontend/constants/index.ts
  apps/frontend/constants/strings/alert.ts
  apps/frontend/constants/strings/index.ts
  apps/frontend/hooks/animations/index.ts
  apps/frontend/hooks/animations/useRipple.tsx
  apps/frontend/hooks/index.ts
  apps/frontend/tailwind.config.js
  apps/frontend/types/props.d.ts
  apps/frontend/utils/index.ts
  apps/frontend/utils/supabase/auth.ts
  apps/frontend/utils/supabase/client.ts
  apps/frontend/utils/supabase/index.ts
  apps/frontend/utils/validations.ts
Labels: feature

#37 Zustand Store for User Profile Management
  apps/frontend/app/(auth)/(signup)/index.tsx
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(profile)/_layout.tsx
  apps/frontend/app/(profile)/edit.tsx
  apps/frontend/app/(profile)/index.tsx
  apps/frontend/app/(tabs)/_layout.tsx
  apps/frontend/app/(tabs)/account.tsx
  apps/frontend/app/index.tsx
  apps/frontend/components/index.ts
  apps/frontend/components/loaders/OverlayLoader.tsx
  apps/frontend/components/loaders/index.ts
  apps/frontend/constants/strings/index.ts
  apps/frontend/store/auth.store.ts
  apps/frontend/store/index.ts
  apps/frontend/types/props.d.ts
  apps/frontend/types/store.d.ts
Labels: feature

#39 Integrates signup and signin with Zustand auth store
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/_layout.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(auth)/welcome.tsx
  apps/frontend/app/(tabs)/_layout.tsx
  apps/frontend/store/auth.store.ts
  apps/frontend/types/store.d.ts
Labels: feature

#40 Design Home Screen with WalletCard, Profile Avatar & Floating Action Button
  apps/frontend/app/(tabs)/_layout.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/assets/images/exchange.png
  apps/frontend/assets/images/wallet-bg.png
  apps/frontend/assets/index.ts
  apps/frontend/components/avatars/InitialsAvatar.tsx
  apps/frontend/components/cards/WalletCard.tsx
  apps/frontend/components/cards/index.ts
  apps/frontend/components/index.ts
  apps/frontend/components/tab/FloatingActionTabButton.tsx
  apps/frontend/components/tab/index.ts
  apps/frontend/package-lock.json
  apps/frontend/package.json
Labels: feature
