Repository leoAshu/crypter, pull requests merged in 2025-08, with the labels that each got.

#49 Refactor AdCard UI & Integrate ChipFilter for P2P Ads
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/app/(tabs)/(profile)/_layout.tsx
  apps/frontend/app/globals.css
  apps/frontend/assets/icons/dark/clock.png
  apps/frontend/assets/icons/dark/tick-square.png
  apps/frontend/assets/icons/light/clock.png
  apps/frontend/assets/icons/light/tick-square.png
  apps/frontend/assets/images/account.png
  apps/frontend/assets/images/arrow-left.png
  apps/frontend/assets/images/couple.png
  apps/frontend/assets/images/exchange.png
  apps/frontend/assets/images/home.png
  apps/frontend/assets/images/like.png
  apps/frontend/assets/images/megaphone.png
  apps/frontend/assets/images/next.png
  apps/frontend/assets/images/receipt.png
  apps/frontend/assets/images/star.png
  apps/frontend/assets/images/stopwatch.png
  apps/frontend/assets/images/tick-square.png
  apps/frontend/assets/index.ts
  apps/frontend/assets/pay-methods/gpay.png
  apps/frontend/assets/pay-methods/imps.png
  apps/frontend/assets/pay-methods/paytm.png
  apps/frontend/assets/pay-methods/phonepe.png
  apps/frontend/assets/pay-methods/upi.png
  apps/frontend/assets/payment-methods/imps.png
  apps/frontend/assets/payment-methods/phonepe.png
  apps/frontend/components/badges/PayMethodBadge.tsx
  apps/frontend/components/badges/PaymentBadge.tsx
  apps/frontend/components/badges/index.ts
  apps/frontend/components/cards/AdCard.tsx
  apps/frontend/components/dividers/DividerX.tsx
  apps/frontend/components/filters/ChipFilter.tsx
  apps/frontend/components/menu/MenuOption.tsx
  apps/frontend/components/tab/HeaderBackAction.tsx
  apps/frontend/models/ad/index.ts
  apps/frontend/models/ad/type.d.ts
  apps/frontend/models/crypto/index.ts
  apps/frontend/models/index.ts
  apps/frontend/models/payMethods/index.ts
  apps/frontend/models/payMethods/type.d.ts
  apps/frontend/tailwind.config.js
  apps/frontend/types/props.d.ts
Labels: enhancement, feature

#52 Implement Orders Screen with Filters, OrderCard, and Toast
  apps/frontend/app/(auth)/_layout.tsx
  apps/frontend/app/(p2p)/_layout.tsx
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/app/(p2p)/orders.tsx
  apps/frontend/app/(tabs)/(profile)/_layout.tsx
  apps/frontend/app/(tabs)/_layout.tsx
  apps/frontend/app/_layout.tsx
  apps/frontend/app/globals.css
  apps/frontend/assets/icons/dark/close-circle.png
  apps/frontend/assets/icons/dark/copy-success.png
  apps/frontend/assets/icons/dark/copy.png
  apps/frontend/assets/icons/dark/info-circle.png
  apps/frontend/assets/icons/dark/tick-circle.png
  apps/frontend/assets/icons/dark/verify-gold.png
  apps/frontend/assets/icons/light/close-circle.png
  apps/frontend/assets/icons/light/copy-success.png
  apps/frontend/assets/icons/light/copy.png
  apps/frontend/assets/icons/light/info-circle.png
  apps/frontend/assets/icons/light/tick-circle.png
  apps/frontend/assets/icons/light/verify-gold.png
  apps/frontend/assets/index.ts
  apps/frontend/components/buttons/FloatingActionButton.tsx
  apps/frontend/components/buttons/index.ts
  apps/frontend/components/cards/AdCard.tsx
  apps/frontend/components/cards/OrderCard.tsx
  apps/frontend/components/cards/index.ts
  apps/frontend/components/form/InputField.tsx
  apps/frontend/components/iconButtons/BackIconButton.tsx
  apps/frontend/components/iconButtons/CopyIconButton.tsx
  apps/frontend/components/iconButtons/IconButton.tsx
  apps/frontend/components/iconButtons/RoundIconButton.tsx
  apps/frontend/components/iconButtons/index.ts
  apps/frontend/components/index.ts
  apps/frontend/components/tab/HeaderActionIcon.tsx
  apps/frontend/components/tab/index.ts
  apps/frontend/components/toasts/SuccessToast.tsx
  apps/frontend/components/toasts/index.tsx
  apps/frontend/constants/index.ts
  apps/frontend/constants/strings/alert.ts
  apps/frontend/constants/strings/components.ts
  apps/frontend/constants/strings/index.ts
  apps/frontend/constants/strings/toast.ts
  apps/frontend/models/index.ts
  apps/frontend/models/order/index.ts
  apps/frontend/models/order/type.d.ts
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/types/props.d.ts
  apps/frontend/utils/index.ts
Labels: enhancement, feature

#55 Migrate to Supabase Profiles Table & Zustand-Based Global Profile Store
  apps/frontend/README.md
  apps/frontend/app.json
  apps/frontend/app/(auth)/welcome.tsx
  apps/frontend/app/(tabs)/(profile)/edit.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/assets/images/logo.png
  apps/frontend/components/account/AccountInfo.tsx
  apps/frontend/constants/strings/index.ts
  apps/frontend/eas.json
  apps/frontend/models/profile/type.d.ts
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/store/auth.store.ts
  apps/frontend/store/index.ts
  apps/frontend/store/profile.store.ts
  apps/frontend/types/props.d.ts
  apps/frontend/types/store.d.ts
  apps/frontend/utils/index.ts
  apps/frontend/utils/supabase/index.ts
  apps/frontend/utils/supabase/mapUtils/index.ts
  apps/frontend/utils/supabase/mapUtils/profile.ts
  apps/frontend/utils/supabase/profile.ts
Labels: enhancement, feature

#57 Fixes Splash Screen and adds build scripts to package.json
  apps/frontend/app.json
  apps/frontend/package.json
  package.json
Labels: bug, enhancement

#59 Dynamic Cryptocurrencies Config via Supabase & Zustand
  apps/frontend/app/(p2p)/(advert)/index.tsx
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/components/cards/AdCard.tsx
  apps/frontend/components/cards/OrderCard.tsx
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useCrypto.tsx
  apps/frontend/hooks/index.ts
  apps/frontend/models/ad/index.ts
  apps/frontend/models/ad/type.d.ts
  apps/frontend/models/crypto/index.ts
  apps/frontend/models/crypto/type.d.ts
  apps/frontend/models/index.ts
  apps/frontend/models/order/index.ts
  apps/frontend/store/auth.store.ts
  apps/frontend/store/crypto.store.ts
  apps/frontend/types/store.d.ts
  apps/frontend/utils/supabase/crypto.ts
  apps/frontend/utils/supabase/index.ts
  apps/frontend/utils/supabase/mapUtils/crypto.ts
  apps/frontend/utils/supabase/mapUtils/index.ts
  apps/frontend/utils/supabase/mapUtils/profile.ts
  apps/frontend/utils/supabase/profile.ts
Labels: enhancement, feature

#61 Dynamic Fiat Currencies Config via Supabase & Zustand
  apps/frontend/app/(p2p)/(advert)/index.tsx
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useAds.tsx
  apps/frontend/hooks/appData/useCrypto.tsx
  apps/frontend/hooks/appData/useFiat.tsx
  apps/frontend/models/ad/index.ts
  apps/frontend/models/fiat/type.d.ts
  apps/frontend/store/auth.store.ts
  apps/frontend/store/crypto.store.ts
  apps/frontend/store/fiat.store.ts
  apps/frontend/store/index.ts
  apps/frontend/store/profile.store.ts
  apps/frontend/supabase/auth.ts
  apps/frontend/supabase/client.ts
  apps/frontend/supabase/crypto.ts
  apps/frontend/supabase/fiat.ts
  apps/frontend/supabase/index.ts
  apps/frontend/supabase/mapUtils/crypto.ts
  apps/frontend/supabase/mapUtils/fiat.ts
  apps/frontend/supabase/mapUtils/index.ts
  apps/frontend/supabase/mapUtils/profile.ts
  apps/frontend/supabase/profile.ts
  apps/frontend/utils/index.ts
Labels: enhancement, feature

#66 Adds PrimaryDropdown
  apps/frontend/app/(p2p)/(advert)/post.tsx
  apps/frontend/components/filters/PrimaryDropdown.tsx
  apps/frontend/components/filters/index.ts
  apps/frontend/types/props.d.ts
Labels: feature

#68 Refactor: Filters, Chip/Toggle Components, and Global Styles for Consistency and Maintainability
  apps/frontend/app/(addFunds)/index.tsx
  apps/frontend/app/(auth)/(signup)/index.tsx
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(p2p)/(advert)/index.tsx
  apps/frontend/app/(p2p)/(advert)/post.tsx
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/app/(p2p)/orders.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/app/globals.css
  apps/frontend/components/account/AccountInfo.tsx
  apps/frontend/components/cards/AdCard.tsx
  apps/frontend/components/cards/AddvertCard.tsx
  apps/frontend/components/filters/ChipFilter.tsx
  apps/frontend/components/filters/Dropdown.tsx
  apps/frontend/components/filters/ToggleButton.tsx
  apps/frontend/components/filters/index.ts
  apps/frontend/components/form/InputField.tsx
  apps/frontend/components/iconButtons/BackIconButton.tsx
  apps/frontend/components/iconButtons/CopyIconButton.tsx
  apps/frontend/components/iconButtons/RoundIconButton.tsx
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useAds.tsx
  apps/frontend/hooks/appData/useCrypto.tsx
  apps/frontend/hooks/appData/useOrders.tsx
  apps/frontend/hooks/appData/useStats.tsx
  apps/frontend/models/ad/index.ts
  apps/frontend/models/ad/type.d.ts
  apps/frontend/models/index.ts
  apps/frontend/models/order/index.ts
  apps/frontend/models/order/type.d.ts
  apps/frontend/models/stats/index.ts
  apps/frontend/models/stats/stats.d.ts
  apps/frontend/store/auth.store.ts
  apps/frontend/store/index.ts
  apps/frontend/store/stats.store.ts
  apps/frontend/store/wallet.store.ts
  apps/frontend/supabase/ad.ts
  apps/frontend/supabase/fiat.ts
  apps/frontend/supabase/mapUtils/stats.ts
  apps/frontend/supabase/stats.ts
  apps/frontend/types/props.d.ts
  apps/frontend/types/store.d.ts
  apps/frontend/utils/index.ts
Labels: enhancement, feature

#70 Implement Reviews & Feedback Feature
  apps/frontend/app/(tabs)/(profile)/_layout.tsx
  apps/frontend/app/(tabs)/(profile)/feedback.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/(tabs)/(profile)/stats.tsx
  apps/frontend/assets/icons/dark/active/dislike.png
  apps/frontend/assets/icons/dark/active/like.png
  apps/frontend/assets/icons/light/active/dislike.png
  apps/frontend/assets/icons/light/active/like.png
  apps/frontend/assets/index.ts
  apps/frontend/components/cards/ReviewCard.tsx
  apps/frontend/components/cards/index.ts
  apps/frontend/constants/strings/index.ts
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useReviews.tsx
  apps/frontend/models/index.ts
  apps/frontend/models/review/index.ts
  apps/frontend/models/review/type.d.ts
  apps/frontend/store/auth.store.ts
  apps/frontend/store/index.ts
  apps/frontend/store/review.store.ts
  apps/frontend/supabase/mapUtils/index.ts
  apps/frontend/supabase/mapUtils/review.ts
  apps/frontend/supabase/review.ts
  apps/frontend/types/props.d.ts
Labels: enhancement, feature

#72 Implements Review Filter
  apps/frontend/app/(tabs)/(profile)/feedback.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/components/cards/ReviewCard.tsx
  apps/frontend/components/menu/MenuOption.tsx
  apps/frontend/hooks/appData/useReviews.tsx
Labels: feature

#73 [HOTFIX] Fixes Light theme Icon for Review type
  apps/frontend/components/cards/ReviewCard.tsx
Labels: bug

#74 Miscellaneous Refactors & Minor Features Implementation
  apps/frontend/app/(addFunds)/index.tsx
  apps/frontend/app/(auth)/(signup)/index.tsx
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(auth)/welcome.tsx
  apps/frontend/app/globals.css
  apps/frontend/components/backgrounds/WalletCardGradient.tsx
  apps/frontend/components/backgrounds/index.ts
  apps/frontend/components/cards/OrderCard.tsx
  apps/frontend/components/cards/WalletCard.tsx
  apps/frontend/components/form/InputField.tsx
  apps/frontend/components/iconButtons/CopyIconButton.tsx
  apps/frontend/constants/strings/index.ts
  apps/frontend/constants/strings/toast.ts
  apps/frontend/hooks/appData/useAds.tsx
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/store/auth.store.ts
  apps/frontend/store/stats.store.ts
  apps/frontend/supabase/stats.ts
  apps/frontend/types/store.d.ts
Labels: bug, enhancement, feature

#76 Home Screen Market Ticker Section Design
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(p2p)/(advert)/post.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/app/index.tsx
  apps/frontend/assets/icons/dark/btc.png
  apps/frontend/assets/icons/dark/eth.png
  apps/frontend/assets/icons/dark/usdt.png
  apps/frontend/assets/icons/light/btc.png
  apps/frontend/assets/icons/light/eth.png
  apps/frontend/assets/icons/light/usdt.png
  apps/frontend/assets/index.ts
  apps/frontend/components/cards/TickerCard.tsx
  apps/frontend/components/cards/WalletCard.tsx
  apps/frontend/components/cards/index.ts
  apps/frontend/components/index.ts
  apps/frontend/components/sections/Market.tsx
  apps/frontend/components/sections/index.ts
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useCrypto.tsx
  apps/frontend/hooks/appData/useMarket.tsx
  apps/frontend/models/ticker/type.d.ts
  apps/frontend/store/index.ts
  apps/frontend/store/market.store.ts
  apps/frontend/types/store.d.ts
  apps/frontend/utils/api.ts
  apps/frontend/utils/index.ts
Labels: feature

#83 Refactor & Enhance AppBar Across Multiple Screens
  apps/frontend/app/(addFunds)/_layout.tsx
  apps/frontend/app/(addFunds)/index.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(p2p)/(advert)/(post)/_layout.tsx
  apps/frontend/app/(p2p)/(advert)/(post)/index.tsx
  apps/frontend/app/(p2p)/(advert)/(post)/info.tsx
  apps/frontend/app/(p2p)/(advert)/_layout.tsx
  apps/frontend/app/(p2p)/(advert)/index.tsx
  apps/frontend/app/(p2p)/_layout.tsx
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/app/(p2p)/orders.tsx
  apps/frontend/app/(tabs)/(profile)/_layout.tsx
  apps/frontend/app/(tabs)/(profile)/edit.tsx
  apps/frontend/app/(tabs)/(profile)/feedback.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/(tabs)/(profile)/stats.tsx
  apps/frontend/app/(tabs)/_layout.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/app/_layout.tsx
  apps/frontend/app/globals.css
  apps/frontend/assets/icons/dark/add-square.png
  apps/frontend/assets/icons/light/add-square.png
  apps/frontend/assets/index.ts
  apps/frontend/components/cards/ReviewCard.tsx
  apps/frontend/components/cards/TickerCard.tsx
  apps/frontend/components/iconButtons/BackIconButton.tsx
  apps/frontend/components/sections/AppBar.tsx
  apps/frontend/components/sections/Market.tsx
  apps/frontend/components/sections/MyAds.tsx
  apps/frontend/components/sections/index.ts
  apps/frontend/components/tab/HeaderActionIcon.tsx
  apps/frontend/components/tab/TabBarIcon.tsx
  apps/frontend/hooks/appData/useStats.tsx
  apps/frontend/types/props.d.ts
Labels: enhancement, feature

#84 Refactor State Management & Haptics Implementation
  apps/frontend/app/(addFunds)/index.tsx
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/(auth)/welcome.tsx
  apps/frontend/app/(p2p)/(advert)/index.tsx
  apps/frontend/app/(p2p)/index.tsx
  apps/frontend/app/(tabs)/(profile)/edit.tsx
  apps/frontend/app/(tabs)/(profile)/feedback.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/(tabs)/index.tsx
  apps/frontend/app/index.tsx
  apps/frontend/assets/icons/dark/info-circle.png
  apps/frontend/assets/icons/dark/warn-circle.png
  apps/frontend/assets/icons/light/info-circle.png
  apps/frontend/assets/icons/light/warn-circle.png
  apps/frontend/assets/index.ts
  apps/frontend/components/buttons/FloatingActionButton.tsx
  apps/frontend/components/cards/AdCard.tsx
  apps/frontend/components/cards/MyAdCard.tsx
  apps/frontend/components/cards/WalletCard.tsx
  apps/frontend/components/filters/ChipFilter.tsx
  apps/frontend/components/filters/ToggleButton.tsx
  apps/frontend/components/filters/ToggleSwitch.tsx
  apps/frontend/constants/strings/toast.ts
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useAuth.tsx
  apps/frontend/hooks/appData/useProfile.tsx
  apps/frontend/hooks/appData/useWallet.tsx
  apps/frontend/utils/haptics.ts
  apps/frontend/utils/index.ts
Labels: enhancement, feature

#88 adds bottom sheet component
  apps/frontend/components/form/BottomSheet.tsx
  apps/frontend/types/props.d.ts
Labels: feature

#89 [HOTFIX] Deposit Screen Crash Fix
  apps/frontend/package-lock.json
  apps/frontend/package.json
Labels: bug

#93 Designs FormInputField
  apps/frontend/components/form/FormInputField.tsx
  apps/frontend/components/form/index.ts
  apps/frontend/types/props.d.ts
Labels: feature

#94 Designs the Verify Index Screen
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/verify/_layout.tsx
  apps/frontend/app/verify/index.tsx
  apps/frontend/assets/images/green-shield-dark.png
  apps/frontend/assets/images/green-shield.png
  apps/frontend/assets/index.ts
  apps/frontend/constants/strings/index.ts
Labels: feature

#95 Designs Requirements Screen
  apps/frontend/app/verify/_layout.tsx
  apps/frontend/app/verify/index.tsx
  apps/frontend/app/verify/requirements.tsx
  apps/frontend/assets/icons/dark/danger.png
  apps/frontend/assets/icons/dark/tickbox-success.png
  apps/frontend/assets/icons/dark/tickbox.png
  apps/frontend/assets/icons/light/danger.png
  apps/frontend/assets/icons/light/tickbox-success.png
  apps/frontend/assets/icons/light/tickbox.png
  apps/frontend/assets/index.ts
  apps/frontend/components/menu/RequirementOption.tsx
  apps/frontend/components/menu/index.ts
  apps/frontend/components/sections/AppBar.tsx
  apps/frontend/constants/strings/index.ts
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useRequirements.tsx
  apps/frontend/models/index.ts
  apps/frontend/models/requirement/index.ts
  apps/frontend/models/requirement/type.d.ts
  apps/frontend/tailwind.config.js
  apps/frontend/types/props.d.ts
Labels: feature

#96 Implement OTP & Verification Screens
  apps/frontend/app/(addFunds)/index.tsx
  apps/frontend/app/globals.css
  apps/frontend/app/verify/[reqId].tsx
  apps/frontend/app/verify/_layout.tsx
  apps/frontend/app/verify/otp.tsx
  apps/frontend/app/verify/requirements.tsx
  apps/frontend/assets/icons/upload.png
  apps/frontend/assets/index.ts
  apps/frontend/components/filters/Dropdown.tsx
  apps/frontend/components/form/FileUpload.tsx
  apps/frontend/components/form/FormInputField.tsx
  apps/frontend/components/form/index.ts
  apps/frontend/components/menu/MenuOption.tsx
  apps/frontend/components/menu/RequirementOption.tsx
  apps/frontend/components/sections/VerifyEmail.tsx
  apps/frontend/components/sections/VerifyIdentity.tsx
  apps/frontend/components/sections/VerifyPhone.tsx
  apps/frontend/components/sections/index.ts
  apps/frontend/constants/strings/components.ts
  apps/frontend/constants/strings/index.ts
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useCountry.tsx
  apps/frontend/hooks/appData/useRequirements.tsx
  apps/frontend/models/country/type.d.ts
  apps/frontend/models/requirement/index.ts
  apps/frontend/models/requirement/type.d.ts
  apps/frontend/package-lock.json
  apps/frontend/package.json
  apps/frontend/types/props.d.ts
  apps/frontend/utils/haptics.ts
Labels: bug, enhancement, feature

#98 [HOTFIX] Removes duplicate interface
  apps/frontend/types/props.d.ts
Labels: bug

#102 Refactor Verify Flow with `NotificationModal`
  apps/frontend/app/(tabs)/(profile)/(pay-methods)/index.tsx
  apps/frontend/app/(tabs)/(profile)/index.tsx
  apps/frontend/app/verify/[reqId].tsx
  apps/frontend/app/verify/otp.tsx
  apps/frontend/app/verify/requirements.tsx
  apps/frontend/assets/icons/dark/clock-halo.png
  apps/frontend/assets/icons/dark/tick-halo.png
  apps/frontend/assets/icons/light/clock-halo.png
  apps/frontend/assets/icons/light/tick-halo.png
  apps/frontend/assets/index.ts
  apps/frontend/components/modals/ModalView.tsx
  apps/frontend/components/modals/NewPayMethodModal.tsx
  apps/frontend/components/modals/NotificationModal.tsx
  apps/frontend/components/modals/SelectPayMethodModal.tsx
  apps/frontend/components/modals/index.ts
  apps/frontend/components/toasts/ErrorToast.tsx
  apps/frontend/components/toasts/index.tsx
  apps/frontend/constants/strings/index.ts
  apps/frontend/constants/strings/toast.ts
  apps/frontend/types/props.d.ts
Labels: enhancement, feature

#103 Implement PhoneInputField Component
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(tabs)/(profile)/edit.tsx
  apps/frontend/app/globals.css
  apps/frontend/components/filters/Dropdown.tsx
  apps/frontend/components/form/PhoneInputField.tsx
  apps/frontend/components/form/SecondaryInputField.tsx
  apps/frontend/components/form/index.ts
  apps/frontend/components/sections/VerifyIdentity.tsx
  apps/frontend/components/sections/VerifyPhone.tsx
  apps/frontend/hooks/appData/useCountry.tsx
  apps/frontend/types/props.d.ts
  apps/frontend/utils/index.ts
Labels: enhancement, feature

#105 Fix SignIn Bug After App Reload
  apps/frontend/app/(auth)/(signup)/index.tsx
  apps/frontend/app/(auth)/(signup)/info.tsx
  apps/frontend/app/(auth)/signin.tsx
  apps/frontend/app/index.tsx
  apps/frontend/store/appData.store.ts
  apps/frontend/store/auth.store.ts
  apps/frontend/store/index.ts
  apps/frontend/store/kyc.store.ts
  apps/frontend/types/store.d.ts
Labels: bug, enhancement

#106 Refactor Hooks into appData and userData Folders
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/index.ts
  apps/frontend/hooks/userData/index.ts
  apps/frontend/hooks/userData/useAuth.tsx
  apps/frontend/hooks/userData/useKyc.tsx
  apps/frontend/hooks/userData/useOrders.tsx
  apps/frontend/hooks/userData/usePayMethod.tsx
  apps/frontend/hooks/userData/useProfile.tsx
  apps/frontend/hooks/userData/useReviews.tsx
  apps/frontend/hooks/userData/useStats.tsx
  apps/frontend/hooks/userData/useWallet.tsx
Labels: enhancement

#107 Enhances advert posting with fiat selection, payment limits, UI updates, and refactored components
  apps/frontend/app/(p2p)/(advert)/(post)/index.tsx
  apps/frontend/app/(p2p)/(advert)/(post)/info.tsx
  apps/frontend/app/globals.css
  apps/frontend/assets/icons/dark/active/add-circle.png
  apps/frontend/assets/icons/dark/active/minus-cirlce.png
  apps/frontend/assets/icons/dark/inactive/add-circle.png
  apps/frontend/assets/icons/dark/inactive/minus-cirlce.png
  apps/frontend/assets/icons/decrement.png
  apps/frontend/assets/icons/increment.png
  apps/frontend/assets/icons/light/active/add-circle.png
  apps/frontend/assets/icons/light/active/minus-cirlce.png
  apps/frontend/assets/icons/light/inactive/add-circle.png
  apps/frontend/assets/icons/light/inactive/minus-cirlce.png
  apps/frontend/assets/index.ts
  apps/frontend/components/filters/Dropdown.tsx
  apps/frontend/components/form/PaymentMethodChips.tsx
  apps/frontend/components/form/StepperInput.tsx
  apps/frontend/components/form/index.ts
  apps/frontend/components/iconButtons/IndexIconButton.tsx
  apps/frontend/components/modals/NotificationModal.tsx
  apps/frontend/components/modals/PayTimeLimitModal.tsx
  apps/frontend/components/modals/index.ts
  apps/frontend/constants/strings/index.ts
  apps/frontend/hooks/appData/index.ts
  apps/frontend/hooks/appData/useFiat.tsx
  apps/frontend/hooks/appData/usePaymentTimeLimits.tsx
  apps/frontend/types/props.d.ts
Labels: bug, enhancement, feature

#109 Handle Empty State for Feedback Screen with Custom FeedbackEmptyState Component
  apps/frontend/app/(tabs)/(profile)/feedback.tsx
  apps/frontend/assets/icons/dark/message-favorite.png
  apps/frontend/assets/icons/light/message-favorite.png
  apps/frontend/assets/index.ts
Labels: enhancement

#112 Enhance Post Advert UI with 'Order Type' label and improved ToggleButton layout
  apps/frontend/app/(p2p)/(advert)/(post)/index.tsx
  apps/frontend/constants/strings/index.ts
Labels: enhancement

#113 Refactors payment method selection
  apps/frontend/app/(p2p)/(advert)/(post)/info.tsx
  apps/frontend/components/modals/SelectPayMethodModal.tsx
  apps/frontend/hooks/userData/usePayMethod.tsx
Labels: enhancement, feature
